import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Enhedsterapi Hillerød - Om klinikken</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>About</h1>
    </div>
  );
};

export default About;
