import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/hero";
import Paragraph from "../components/paragraph";
import TextImage from "../components/textImage";
import Quote from "../components/quote";

const Home: NextPage = () => {
  const heroContent = {
    title:
      "Enhedsterapi vækker menneskets ressourcer og selvhelbredende evner.",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pretium egestas porta consectetur arcu, ipsum at.",
    buttonMore: {
      text: "Læs mere",
      url: "/behandling",
    },
    buttonBook: {
      text: "Book tid",
      url: "/kontakt",
    },
    image: {
      src: "/images/blomsterhave.jpg",
      alt: "Blomsterhave med et lyserødt træ",
    },
    bg: "theme",
  };

  const paragraphContent = {
    title: "Hvad kan enhedsterapi gøre for dig?",
    text: "At hjælpe det enkelte menneske, patient eller klient til at hjælpe sig selv i mange forskellige former for problemstillinger. Princippet er at styrke personlige evner, ressourcer og muligheder uanset funktionsniveauet, samt at arbejde ud fra den enkeltes kontekst med familie- og psykosocial baggrund. Ved samarbejde mellem behandler og klient at op fælles resonans og respons. Der er mange forskellige redskaber og nogle af dem er specielt effektive i forbindelse med stress, traumer, chok og fobier (jævnf.  Slavinski).",
  };

  const textImageContent = {
    title: "Enhedsterapeut\nLisbeth Jessen",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet tincidunt ante imperdiet vel pellentesque nec sed. Amet in placerat netus faucibus. Etiam diam eget at diam, at ridiculus sem magna. Commodo, lacus, quisque tellus, orci nisi, feugiat. Dictum non sed placerat donec semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet tincidunt ante imperdiet vel pellentesque nec sed. Amet in placerat netus faucibus. Etiam diam eget at diam, at ridiculus sem magna. Commodo, lacus, quisque tellus, orci nisi, feugiat. Dictum non sed placerat donec semper.",
    button: {
      text: "Læs mere",
      url: "/klinik",
    },
    image: {
      src: "/images/lisbeth-jessen.jpg",
      alt: "Enhedsterapeut Lisbeth Jessen",
    },
    position: "right",
    bg: "sand",
  };

  const quoteContent = {
    quote:
      "“Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pulvinar turpis tristique amet, consectetur cursus.”",
    author: "// Klient eller citat person",
    image: {
      src: "/images/solnedgang.jpg",
      alt: "Solnedgang ved Arresø",
    },
  };

  return (
    <>
      <Head>
        <title>Enhedsterapi Hillerød</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero {...heroContent} />
      <Paragraph {...paragraphContent} />
      <TextImage {...textImageContent} />
      <Quote {...quoteContent} />
    </>
  );
};

export default Home;
