import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/hero";
import TextImage from "../components/textImage";
import FaqContainer from "../components/faq/FaqContainer";
import FaqItem from "../components/faq/FaqItem";
import FAQ from "../components/faq";

const About: NextPage = () => {
  const heroContent = {
    title:
      "“Et quote eller ordsprog din mor syntes giver mening til siden om hende og klinikken”",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pretium egestas porta consectetur arcu, ipsum at.",
    image: {
      src: "/images/krystal.jpg",
      alt: "En krystal på et bord",
    },
    bg: "brown",
  };

  const textImageContentFirst = {
    title: "Enhedsterapeut\nLisbeth Jessen",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet tincidunt ante imperdiet vel pellentesque nec sed. Amet in placerat netus faucibus. Etiam diam eget at diam, at ridiculus sem magna. Commodo, lacus, quisque tellus, orci nisi, feugiat. Dictum non sed placerat donec semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet tincidunt ante imperdiet vel pellentesque nec sed. Amet in placerat netus faucibus. Etiam diam eget at diam, at ridiculus sem magna. Commodo, lacus, quisque tellus, orci nisi, feugiat. Dictum non sed placerat donec semper.",
    image: {
      src: "/images/krystal.jpg",
      alt: "Enhedsterapeut Lisbeth Jessen",
    },
    position: "left",
  };

  const textImageContentSecond = {
    title: "Enhedsterapeut\nLisbeth Jessen",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet tincidunt ante imperdiet vel pellentesque nec sed. Amet in placerat netus faucibus. Etiam diam eget at diam, at ridiculus sem magna. Commodo, lacus, quisque tellus, orci nisi, feugiat. Dictum non sed placerat donec semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet tincidunt ante imperdiet vel pellentesque nec sed. Amet in placerat netus faucibus. Etiam diam eget at diam, at ridiculus sem magna. Commodo, lacus, quisque tellus, orci nisi, feugiat. Dictum non sed placerat donec semper.",
    image: {
      src: "/images/krystal.jpg",
      alt: "Enhedsterapeut Lisbeth Jessen",
    },
    position: "right",
    bg: "theme",
    validation: true,
  };

  const faqContent = {
    question: "",
    answer: "",
  };

  return (
    <>
      <Head>
        <title>Enhedsterapi Hillerød - Om klinikken</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero {...heroContent} />
      <TextImage {...textImageContentFirst} />
      <TextImage {...textImageContentSecond} />
      <FaqContainer>
        <FaqItem
          question="Hvad er enhedsterapi?"
          answer="Det ved min mor! :-)"
        />
        <FaqItem
          question="Hvad kan en enhedsterapeut gøre for dig?"
          answer="Det ved min mor også! :-)"
        />
      </FaqContainer>
    </>
  );
};

export default About;
